### ISSUE TITLE
Environment variable or setting for column number information

### ISSUE THREAD

**Issue by VlachJosef** [Duhemm/sbt-errors-summary#14]
Current sbt output complete lacks column number information. It has been added into sbt 1.0 in this PR: https://github.com/sbt/zinc/pull/183.

Would it be possible to have same means to show column number in similar way to what is proposed in https://github.com/Duhemm/sbt-errors-summary/issues/13 for full path?

For tools which supports automatic navigation to the error location from sbt output, full file name, row and column are essential informations to achieve that.
```
[error] [1] /Users/me/column/src/main/scala/Column.scala:5:31:
[error]  type mismatch;
```

To be able to get output like this would be great.

**Comment by fommil** [comment]
just pointing out the prior art https://github.com/ensime/emacs-sbt-mode/pull/86

**Comment by Duhemm** [comment]
@VlachJosef Would #16 be an acceptable solution for you?

**Comment by VlachJosef** [comment]
@Duhemm it exactly what I had in mind.

I now just wonder, since it is just couple of extra chars on the line, is that special flag for it necessary? Wouldn't it be better option to keep it there all the time?

**Comment by Duhemm** [comment]
I personally prefer to show only the information that is actually useful. I don't think many humans will look at the column number and use that information, and I think it makes it easier to read the line number if that's the only number that is present.

Do you want the column number to be shown for reasons other than tooling support?

**Comment by VlachJosef** [comment]
What is useful information is really personal matter to a big degree here.

And yes, tooling is main reason. I'm constantly being amazed, that people actually read this information and than go to search the line in the said file, instead of a tools to do that for them.

And maybe the way how to improve tooling is to add this information there by default, because than someone may realise, gosh there are all information on the tip of my hand to take me to that exact place in the file.
