### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by francisdb** [Duhemm/sbt-errors-summary#3]
Would you mind setting up maven central sync so users don't need to add an extra repository to use this plugin?

**Comment by Duhemm** [comment]
Hey @francisdb, thanks for the suggestion!

I linked this package to the sbt-plugins-release repository, so you should be able to use it without adding any new repository. Does that work for you?

**Comment by francisdb** [comment]
```
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.duhemm/sbt-errors-summary/scala_2.10/sbt_0.13/0.2.0/jars/sbt-errors-summary.jar ...
[info] 	[SUCCESSFUL ] org.duhemm#sbt-errors-summary;0.2.0!sbt-errors-summary.jar (2093ms)
```

🎉
