### ISSUE TITLE
Use bold colors

### ISSUE THREAD

**Issue by japgolly** [Duhemm/sbt-errors-summary#8]
With the default colour schemes for xTerm, Linux console, Rxvt, the dark blue on black background is near unreadable. Bold blue would be much better. Red is similar but not as bad:

![image](https://user-images.githubusercontent.com/202935/27810415-4d4a4474-609d-11e7-8081-173024604364.png)

**Comment by japgolly** [comment]
I was thinking it might be an idea to make all the colours configurable but on the other hand, it's just as easy to fork and local publish for oneself. I made mine look like this:

![image](https://user-images.githubusercontent.com/202935/27810569-55e4619e-609f-11e7-99b9-c710d91ffb5f.png)

**Comment by Duhemm** [comment]
Thanks for the report! I just tried your branch. The result of your whole set of changes look really good, and make everything even easier to read.

Would you mind opening a PR with your config?

**Comment by japgolly** [comment]
Yeah I was going to ask you about that. I made a bunch more changes, are you happy with all of them? I can create a PR with all the changes or just a subset that you're happy with.

To summarise my changes:
* changed colours of filenames
* made most colours bold so they are more readable on black backgrounds (at least in my envs)
* in the by-filename report at the end
  * sort by filename
  * only print if more than one file
  * print total error/warning count per file
  * don't print line numbers
  * consolidate problem ids where possible (eg. `[1-4,9]` instead of `[1,2,3,4,9]`)
* print total errors and warnings

**Comment by Duhemm** [comment]
All of them sound good to me! Looking forward to the PR!

**Comment by japgolly** [comment]
Great, I'll get a PR ready later this week!

**Comment by Duhemm** [comment]
Hey @japgolly, I've been looking in more details at your changes, and I had missed that you removed the line numbers from the summary. That's basically the reason why I created this reporter :( Can you think of a way of adapting your changes while keeping the line numbers from the summary? Maybe a flag that would let users switch between the 2 modes?

**Comment by Duhemm** [comment]
@japgolly Colors and such are now completely configurable. You can set, for instance:

```scala
reporterConfig := reporterConfig.value.withErrorIdColor(BLUE + BOLD)
                                      .withSourcePathColor(YELLOW + UNDERLINED)
```
